import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_OPPORTUNITY } from 'src/modules/opportunity/standard-objects/opportunity.workspace-entity';

export const buildOpportunityStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'opportunity', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'opportunity'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIReadOnly: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Opportunity-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`The opportunity name`),
      icon: 'IconTargetArrow',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  amount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'amount',
      type: FieldMetadataType.CURRENCY,
      label: i18nLabel(msg`Amount`),
      description: i18nLabel(msg`Opportunity amount`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  closeDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'closeDate',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Close date`),
      description: i18nLabel(msg`Opportunity close date`),
      icon: 'IconCalendarEvent',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  stage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'stage',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Stage`),
      description: i18nLabel(msg`Opportunity stage`),
      icon: 'IconProgressCheck',
      isNullable: false,
      defaultValue: "'NEW'",
      options: [
        {
          id: '20202020-8e01-4afd-9c39-d2063097587a',
          value: 'NEW',
          label: i18nLabel(msg`New`),
          position: 0,
          color: 'red',
        },
        {
          id: '20202020-e685-4671-ac32-26d304dacb6e',
          value: 'SCREENING',
          label: i18nLabel(msg`Screening`),
          position: 1,
          color: 'purple',
        },
        {
          id: '20202020-dde9-4acc-b5ca-f6531a8ecb4a',
          value: 'MEETING',
          label: i18nLabel(msg`Meeting`),
          position: 2,
          color: 'sky',
        },
        {
          id: '20202020-696e-4f6b-91bc-f413e9b2f654',
          value: 'PROPOSAL',
          label: i18nLabel(msg`Proposal`),
          position: 3,
          color: 'turquoise',
        },
        {
          id: '20202020-0bb5-4a6f-a8b2-774bbad21104',
          value: 'CUSTOMER',
          label: i18nLabel(msg`Customer`),
          position: 4,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Opportunity record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_OPPORTUNITY,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  pointOfContact: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'pointOfContact',
      label: i18nLabel(msg`Point of Contact`),
      description: i18nLabel(msg`Opportunity point of contact`),
      icon: 'IconUser',
      isNullable: true,
      targetObjectName: 'person',
      targetFieldName: 'pointOfContactForOpportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'pointOfContactId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: i18nLabel(msg`Company`),
      description: i18nLabel(msg`Opportunity company`),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'opportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  favorites: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'favorites',
      label: i18nLabel(msg`Favorites`),
      description: i18nLabel(msg`Favorites linked to the opportunity`),
      icon: 'IconHeart',
      isNullable: true,
      targetObjectName: 'favorite',
      targetFieldName: 'opportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: i18nLabel(msg`Tasks`),
      description: i18nLabel(msg`Tasks tied to the opportunity`),
      icon: 'IconCheckbox',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Notes tied to the opportunity`),
      icon: 'IconNotes',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: i18nLabel(msg`Attachments`),
      description: i18nLabel(msg`Attachments linked to the opportunity`),
      icon: 'IconFileImport',
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(msg`Timeline Activities`),
      description: i18nLabel(
        msg`Timeline Activities linked to the opportunity.`,
      ),
      icon: 'IconTimelineEvent',
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetOpportunity',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  owner: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'owner',
      label: i18nLabel(msg`Owner`),
      description: i18nLabel(msg`Opportunity owner`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'workspaceMember',
      targetFieldName: 'ownedOpportunities',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'ownerId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // --- POP Creations custom fields ---
  programType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'programType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Program Type`),
      description: i18nLabel(msg`Program type`),
      icon: 'IconCategory',
      isNullable: true,
      options: [
        {
          id: '05c3f9f3-736c-48d3-a107-73f501f96f37',
          value: 'LICENSED_PROGRAM',
          label: i18nLabel(msg`Licensed Program`),
          position: 0,
          color: 'purple',
        },
        {
          id: '7cca6c88-21f7-409a-ad9c-622a2d9ed848',
          value: 'REGULAR_ORDER',
          label: i18nLabel(msg`Regular Order`),
          position: 1,
          color: 'blue',
        },
        {
          id: '7c9ce293-9c65-43d5-88ab-248596a6c3ac',
          value: 'FLOOR_RESET',
          label: i18nLabel(msg`Floor Reset`),
          position: 2,
          color: 'orange',
        },
        {
          id: '6e6ce13d-329a-4a7d-ab7c-b70cdd7f70dc',
          value: 'REORDER',
          label: i18nLabel(msg`Reorder`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  seasonYear: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'seasonYear',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Season/Year`),
      description: i18nLabel(msg`Season and year`),
      icon: 'IconCalendar',
      isNullable: true,
      options: [
        {
          id: 'f097bbab-9ad4-431d-a6f3-ca206a34f4d3',
          value: 'SPRING_2026',
          label: i18nLabel(msg`Spring 2026`),
          position: 0,
          color: 'green',
        },
        {
          id: '1931085b-26f1-4713-970f-b9f33bf367e6',
          value: 'BACK_TO_SCHOOL_2026',
          label: i18nLabel(msg`Back to School 2026`),
          position: 1,
          color: 'blue',
        },
        {
          id: 'eb7a930d-8f7c-404d-be70-1442f156a4ed',
          value: 'HOLIDAY_2026',
          label: i18nLabel(msg`Holiday 2026`),
          position: 2,
          color: 'red',
        },
        {
          id: '08f86aa6-72eb-446b-941f-0a241b37fd94',
          value: 'SPRING_2027',
          label: i18nLabel(msg`Spring 2027`),
          position: 3,
          color: 'turquoise',
        },
        {
          id: 'b5a42b82-d1d7-4890-9976-2874077dbf41',
          value: 'BACK_TO_SCHOOL_2027',
          label: i18nLabel(msg`Back to School 2027`),
          position: 4,
          color: 'sky',
        },
        {
          id: '8a99d654-4252-45be-9596-ed27690fd9d0',
          value: 'HOLIDAY_2027',
          label: i18nLabel(msg`Holiday 2027`),
          position: 5,
          color: 'pink',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  directiveSource: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'directiveSource',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Directive Source`),
      description: i18nLabel(msg`Directive source`),
      icon: 'IconArrowRight',
      isNullable: true,
      options: [
        {
          id: '67f02f5d-cf68-41f8-aa51-56526e11e5ce',
          value: 'BUYER_INITIATED',
          label: i18nLabel(msg`Buyer Initiated`),
          position: 0,
          color: 'blue',
        },
        {
          id: '1b8d70e4-81eb-406d-a8bf-621eb778b140',
          value: 'INTERNAL',
          label: i18nLabel(msg`Internal`),
          position: 1,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  division: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'division',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Division`),
      description: i18nLabel(msg`Division`),
      icon: 'IconBriefcase',
      isNullable: true,
      options: [
        {
          id: 'd1',
          value: 'POP',
          label: i18nLabel(msg`POP`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'd2',
          value: 'SPRUCE',
          label: i18nLabel(msg`Spruce`),
          position: 1,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  originCountry: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'originCountry',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Origin Country`),
      description: i18nLabel(msg`Origin country`),
      icon: 'IconGlobe',
      isNullable: true,
      options: [
        {
          id: '676eec73-eff0-4781-8029-7a772f707aca',
          value: 'CHINA',
          label: i18nLabel(msg`China`),
          position: 0,
          color: 'red',
        },
        {
          id: 'a5ff89f3-8f09-43d0-a16a-0c12bfbef9e5',
          value: 'INDIA',
          label: i18nLabel(msg`India`),
          position: 1,
          color: 'orange',
        },
        {
          id: '13b2153b-9bee-4717-887d-245d614090c1',
          value: 'OTHER',
          label: i18nLabel(msg`Other`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  customerIncoterms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'customerIncoterms',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Customer Incoterms`),
      description: i18nLabel(msg`Customer incoterms`),
      icon: 'IconShip',
      isNullable: true,
      options: [
        {
          id: 'dcf0a600-9288-4268-b091-21f15e7aa8de',
          value: 'FOB_CHINA',
          label: i18nLabel(msg`FOB China`),
          position: 0,
          color: 'blue',
        },
        {
          id: '6d13ae84-ff18-4148-a1e2-ed24b8cf8dbe',
          value: 'FOB_INDIA',
          label: i18nLabel(msg`FOB India`),
          position: 1,
          color: 'sky',
        },
        {
          id: 'ab80cf7e-2e7f-4513-b8b8-3ee0c806b3b7',
          value: 'POE_LA',
          label: i18nLabel(msg`POE LA`),
          position: 2,
          color: 'green',
        },
        {
          id: '5760dc8a-dfe5-469e-a383-8cf1f9131da3',
          value: 'POE_NJ',
          label: i18nLabel(msg`POE NJ`),
          position: 3,
          color: 'turquoise',
        },
        {
          id: 'e2fa076a-89e3-4c1c-bf66-cb96b5a00c54',
          value: 'DDP_CHINA',
          label: i18nLabel(msg`DDP China`),
          position: 4,
          color: 'orange',
        },
        {
          id: 'fb47e409-e1b6-47d3-a7ce-34db500ec171',
          value: 'WHSE_LA',
          label: i18nLabel(msg`Whse LA`),
          position: 5,
          color: 'purple',
        },
        {
          id: 'a922ef1a-badc-4ed0-8b60-aad27db04e99',
          value: 'WHSE_NJ',
          label: i18nLabel(msg`Whse NJ`),
          position: 6,
          color: 'pink',
        },
        {
          id: 'c2ea0026-1803-4d28-8b64-d6feebc8f550',
          value: 'WHSE_SPIRIT',
          label: i18nLabel(msg`Whse Spirit`),
          position: 7,
          color: 'yellow',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  factoryIncoterms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'factoryIncoterms',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Factory Incoterms`),
      description: i18nLabel(msg`Factory incoterms`),
      icon: 'IconShip',
      isNullable: true,
      options: [
        {
          id: '93e67e95-da8c-4863-9687-23d9c152ccde',
          value: 'FOB_CHINA',
          label: i18nLabel(msg`FOB China`),
          position: 0,
          color: 'blue',
        },
        {
          id: 'a751ef9b-b873-4cfc-9010-ee03f34f07ac',
          value: 'FOB_INDIA',
          label: i18nLabel(msg`FOB India`),
          position: 1,
          color: 'sky',
        },
        {
          id: '6eeb57be-4eed-4fff-a37f-7d49d6a8a6e3',
          value: 'LDP_LA',
          label: i18nLabel(msg`LDP LA`),
          position: 2,
          color: 'green',
        },
        {
          id: '9264cac8-45f3-4523-96e0-2971f23a6799',
          value: 'LDP_NJ',
          label: i18nLabel(msg`LDP NJ`),
          position: 3,
          color: 'turquoise',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sampleApprovalMethod: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sampleApprovalMethod',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Sample Approval Method`),
      description: i18nLabel(msg`Sample approval method`),
      icon: 'IconPhoto',
      isNullable: true,
      options: [
        {
          id: '72aca642-ca89-42d4-b5c5-282ff5bc056b',
          value: 'IN_PERSON',
          label: i18nLabel(msg`In-Person`),
          position: 0,
          color: 'blue',
        },
        {
          id: '2203541f-294b-483a-bdea-2a375a468fb6',
          value: 'PHOTO',
          label: i18nLabel(msg`Photo`),
          position: 1,
          color: 'green',
        },
        {
          id: 'c13caa19-ef5f-414c-b0a9-811d3fcf6452',
          value: 'NA',
          label: i18nLabel(msg`N/A`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  productionPoNumber: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'productionPoNumber',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Production PO#`),
      description: i18nLabel(msg`Production PO number`),
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  salesOrderNumber: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'salesOrderNumber',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Sales Order#`),
      description: i18nLabel(msg`Sales order number`),
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  importPoNumber: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'importPoNumber',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Import PO#`),
      description: i18nLabel(msg`Import PO number`),
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  clickupTaskId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clickupTaskId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`ClickUp Task ID`),
      description: i18nLabel(msg`ClickUp task ID`),
      icon: 'IconExternalLink',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  clickupStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'clickupStatus',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`ClickUp Status`),
      description: i18nLabel(msg`ClickUp status`),
      icon: 'IconStatusChange',
      isNullable: true,
      isUIReadOnly: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  plmProjectId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'plmProjectId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`PLM Project ID`),
      description: i18nLabel(msg`PLM project ID`),
      icon: 'IconExternalLink',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  licensed: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'licensed',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Licensed`),
      description: i18nLabel(msg`Licensed`),
      icon: 'IconCertificate',
      isNullable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sampleRequired: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sampleRequired',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Sample Required`),
      description: i18nLabel(msg`Sample required`),
      icon: 'IconPackage',
      isNullable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  requiresNewPricing: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'requiresNewPricing',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Requires New Pricing`),
      description: i18nLabel(msg`Requires new pricing`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  hardDeliveryDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'hardDeliveryDate',
      type: FieldMetadataType.DATE,
      label: i18nLabel(msg`Hard Delivery Date`),
      description: i18nLabel(msg`Hard delivery date`),
      icon: 'IconCalendarDue',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  department: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'department',
      label: i18nLabel(msg`Department`),
      description: i18nLabel(msg`Department`),
      icon: 'IconBuildingStore',
      isNullable: true,
      targetObjectName: 'department',
      targetFieldName: 'programs',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'departmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  factory: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'factory',
      label: i18nLabel(msg`Factory`),
      description: i18nLabel(msg`Factory`),
      icon: 'IconBuildingFactory',
      isNullable: true,
      targetObjectName: 'factory',
      targetFieldName: 'programs',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'factoryId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  licensorApprovalThreads: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'licensorApprovalThreads',
      label: i18nLabel(msg`Licensor Approval Threads`),
      description: i18nLabel(msg`Licensor approval threads`),
      icon: 'IconCertificate',
      isNullable: true,
      targetObjectName: 'licensorApprovalThread',
      targetFieldName: 'program',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  emailMessages: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'emailMessages',
      label: i18nLabel(msg`Email Messages`),
      description: i18nLabel(msg`Email messages`),
      icon: 'IconMail',
      isNullable: true,
      targetObjectName: 'emailMessage',
      targetFieldName: 'program',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  meetingNotes: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'meetingNotes',
      label: i18nLabel(msg`Meeting Notes`),
      description: i18nLabel(msg`Meeting notes`),
      icon: 'IconNotes',
      isNullable: true,
      targetObjectName: 'meetingNote',
      targetFieldName: 'program',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
