import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_PERSON } from 'src/modules/person/standard-objects/person.workspace-entity';

export const buildPersonStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'person', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'person'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIReadOnly: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Person-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.FULL_NAME,
      label: i18nLabel(msg`Name`),
      description: "Contact's name",
      icon: 'IconUser',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  emails: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'emails',
      type: FieldMetadataType.EMAILS,
      label: i18nLabel(msg`Emails`),
      description: "Contact's Emails",
      icon: 'IconMail',
      isNullable: true,
      isUnique: true,
      settings: {
        maxNumberOfValues: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  linkedinLink: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'linkedinLink',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Linkedin`),
      description: "Contact's Linkedin account",
      icon: 'IconBrandLinkedin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  xLink: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'xLink',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`X`),
      description: "Contact's X/Twitter account",
      icon: 'IconBrandX',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  jobTitle: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'jobTitle',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Job Title`),
      description: "Contact's job title",
      icon: 'IconBriefcase',
      isNullable: true,
      options: [
        {
          id: 'f4818edf-be39-48ed-91e1-896249f92834',
          color: 'blue',
          label: 'Buyer',
          value: 'BUYER',
          position: 0,
        },
        {
          id: '09fa2c27-1ce6-4059-b603-70c1c94f11c6',
          color: 'sky',
          label: 'Assistant Buyer',
          value: 'ASSISTANT_BUYER',
          position: 1,
        },
        {
          id: '8d8bf9bf-da25-4c49-be9d-2e191061e3d5',
          color: 'purple',
          label: 'Planner',
          value: 'PLANNER',
          position: 2,
        },
        {
          id: 'e3e9986d-c38f-4d68-b840-e509cb58f090',
          color: 'orange',
          label: 'China Office',
          value: 'CHINA_OFFICE',
          position: 3,
        },
        {
          id: '95aed2b7-f7d4-4e1e-ab2e-5909b97717fc',
          color: 'green',
          label: 'Logistics',
          value: 'LOGISTICS',
          position: 4,
        },
        {
          id: '271d6ed3-812e-4452-8fef-6b9bc7274ba3',
          color: 'yellow',
          label: 'Legal',
          value: 'LEGAL',
          position: 5,
        },
        {
          id: 'd588170a-50f5-437b-b5aa-edd0a07844ac',
          color: 'turquoise',
          label: 'Finance',
          value: 'FINANCE',
          position: 6,
        },
        {
          id: 'f4d8b1cb-993e-42db-9169-3dd8e36af740',
          color: 'gray',
          label: 'Other',
          value: 'OTHER',
          position: 7,
        },
        {
          id: 'a2b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d',
          color: 'red',
          label: 'Former Contact',
          value: 'FORMER_CONTACT',
          position: 8,
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  phones: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'phones',
      type: FieldMetadataType.PHONES,
      label: i18nLabel(msg`Phones`),
      description: "Contact's phone numbers",
      icon: 'IconPhone',
      isNullable: true,
      settings: {
        maxNumberOfValues: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  city: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'city',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`City`),
      description: "Contact's city",
      icon: 'IconMap',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  //deprecated
  avatarUrl: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'avatarUrl',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Avatar`),
      description: "Contact's avatar",
      icon: 'IconFileUpload',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  avatarFile: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'avatarFile',
      type: FieldMetadataType.FILES,
      label: i18nLabel(msg`Avatar File`),
      description: "Contact's avatar file",
      icon: 'IconFileUpload',
      isSystem: true,
      isNullable: true,
      settings: {
        maxNumberOfValues: 1,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Person record Position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  company: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'company',
      label: i18nLabel(msg`Company`),
      description: "Contact's company",
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      targetObjectName: 'company',
      targetFieldName: 'people',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'companyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pointOfContactForOpportunities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'pointOfContactForOpportunities',
      label: i18nLabel(msg`Opportunities`),
      description: i18nLabel(
        msg`List of opportunities for which that person is the point of contact`,
      ),
      icon: 'IconTargetArrow',
      isNullable: true,
      targetObjectName: 'opportunity',
      targetFieldName: 'pointOfContact',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  taskTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'taskTargets',
      label: i18nLabel(msg`Tasks`),
      description: i18nLabel(msg`Tasks tied to the contact`),
      icon: 'IconCheckbox',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'taskTarget',
      targetFieldName: 'targetPerson',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  noteTargets: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'noteTargets',
      label: i18nLabel(msg`Notes`),
      description: i18nLabel(msg`Notes tied to the contact`),
      icon: 'IconNotes',
      isUIReadOnly: true,
      isNullable: true,
      targetObjectName: 'noteTarget',
      targetFieldName: 'targetPerson',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  attachments: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'attachments',
      label: i18nLabel(msg`Attachments`),
      description: i18nLabel(msg`Attachments linked to the contact.`),
      icon: 'IconFileImport',
      isNullable: true,
      targetObjectName: 'attachment',
      targetFieldName: 'targetPerson',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  messageParticipants: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'messageParticipants',
      label: i18nLabel(msg`Message Participants`),
      description: i18nLabel(msg`Message Participants`),
      icon: 'IconUserCircle',
      isNullable: true,
      targetObjectName: 'messageParticipant',
      targetFieldName: 'person',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  calendarEventParticipants: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'calendarEventParticipants',
      label: i18nLabel(msg`Calendar Event Participants`),
      description: i18nLabel(msg`Calendar Event Participants`),
      icon: 'IconCalendar',
      isNullable: true,
      targetObjectName: 'calendarEventParticipant',
      targetFieldName: 'person',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      label: i18nLabel(msg`Events`),
      description: i18nLabel(msg`Events linked to the person`),
      icon: 'IconTimelineEvent',
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetPerson',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_PERSON,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // --- POP Creations custom fields ---
  contactType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'contactType',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Contact Type`),
      description: i18nLabel(msg`The type of contact`),
      icon: 'IconUserCircle',
      isNullable: true,
      options: [
        {
          id: 'f4818edf-be39-48ed-91e1-896249f92834',
          color: 'blue',
          label: 'Buyer',
          value: 'BUYER',
          position: 0,
        },
        {
          id: '09fa2c27-1ce6-4059-b603-70c1c94f11c6',
          color: 'sky',
          label: 'Assistant Buyer',
          value: 'ASSISTANT_BUYER',
          position: 1,
        },
        {
          id: '8d8bf9bf-da25-4c49-be9d-2e191061e3d5',
          color: 'purple',
          label: 'Planner',
          value: 'PLANNER',
          position: 2,
        },
        {
          id: 'e3e9986d-c38f-4d68-b840-e509cb58f090',
          color: 'orange',
          label: 'China Office',
          value: 'CHINA_OFFICE',
          position: 3,
        },
        {
          id: '95aed2b7-f7d4-4e1e-ab2e-5909b97717fc',
          color: 'green',
          label: 'Logistics',
          value: 'LOGISTICS',
          position: 4,
        },
        {
          id: '271d6ed3-812e-4452-8fef-6b9bc7274ba3',
          color: 'yellow',
          label: 'Legal',
          value: 'LEGAL',
          position: 5,
        },
        {
          id: 'd588170a-50f5-437b-b5aa-edd0a07844ac',
          color: 'turquoise',
          label: 'Finance',
          value: 'FINANCE',
          position: 6,
        },
        {
          id: 'f4d8b1cb-993e-42db-9169-3dd8e36af740',
          color: 'gray',
          label: 'Other',
          value: 'OTHER',
          position: 7,
        },
        {
          id: 'a2b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d',
          color: 'red',
          label: 'Former Contact',
          value: 'FORMER_CONTACT',
          position: 8,
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  scope: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'scope',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Scope`),
      description: i18nLabel(msg`Controls email routing behavior`),
      icon: 'IconEye',
      isNullable: true,
      options: [
        {
          id: '636ec59b-9558-4233-b163-ef4a765403f5',
          color: 'blue',
          label: 'Department',
          value: 'DEPARTMENT',
          position: 0,
        },
        {
          id: '055a8e14-f033-405a-8e8b-165ba94b525a',
          color: 'green',
          label: 'Company-Wide',
          value: 'COMPANY_WIDE',
          position: 1,
        },
        {
          id: '4a458fd8-0638-4d4c-8446-be551630f954',
          color: 'gray',
          label: 'Ignored',
          value: 'IGNORED',
          position: 2,
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  companyCustomerStatus: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'companyCustomerStatus',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Company Customer Status`),
      description: i18nLabel(
        msg`Auto-synced from the linked Company. Set the Company's status to route this person's emails correctly.`,
      ),
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
      isUIReadOnly: true,
      options: [
        {
          id: 'e4c425d0-e7d7-4283-bffa-3150f98c080b',
          color: 'green',
          label: 'Active Customer',
          value: 'ACTIVE_CUSTOMER',
          position: 0,
        },
        {
          id: '31f0c589-8fc4-411a-98a4-4dae78dc8025',
          color: 'yellow',
          label: 'Potential Customer',
          value: 'POTENTIAL_CUSTOMER',
          position: 1,
        },
        {
          id: '79b1c54f-944a-4af0-9f9a-e8f8a15d6eef',
          color: 'gray',
          label: 'Other',
          value: 'OTHER',
          position: 2,
        },
        {
          id: 'd5e6f7a8-b9c0-4d1e-af3a-4b5c6d7e8f9a',
          color: 'red',
          label: 'New Company',
          value: 'UNASSIGNED',
          position: 3,
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  department: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'department',
      label: i18nLabel(msg`Department`),
      description: i18nLabel(msg`Department this person belongs to`),
      icon: 'IconBuildingStore',
      isNullable: true,
      targetObjectName: 'department',
      targetFieldName: 'people',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'departmentId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  departmentsAsPrimaryBuyer: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'departmentsAsPrimaryBuyer',
      label: i18nLabel(msg`Departments as Primary Buyer`),
      description: i18nLabel(msg`Departments where this person is the primary buyer`),
      icon: 'IconBuildingStore',
      isNullable: true,
      targetObjectName: 'department',
      targetFieldName: 'primaryBuyer',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  meetingAttendances: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'meetingAttendances',
      label: i18nLabel(msg`Meeting Attendances`),
      description: i18nLabel(msg`Meeting notes this person attended`),
      icon: 'IconCalendarEvent',
      isNullable: true,
      targetObjectName: 'meetingNoteAttendee',
      targetFieldName: 'person',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  meetingNotes: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'meetingNotes',
      label: i18nLabel(msg`Meeting Notes`),
      description: i18nLabel(msg`Meeting notes linked to this person`),
      icon: 'IconNotes',
      isNullable: true,
      targetObjectName: 'meetingNote',
      targetFieldName: 'person',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
